// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: market_data.proto
// Protobuf C++ Version: 6.30.2

#ifndef market_5fdata_2eproto_2epb_2eh
#define market_5fdata_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_market_5fdata_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_market_5fdata_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_market_5fdata_2eproto;
}  // extern "C"
class MarketDataEventProto;
struct MarketDataEventProtoDefaultTypeInternal;
extern MarketDataEventProtoDefaultTypeInternal _MarketDataEventProto_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull MarketDataEventProto_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class MarketDataEventProto final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:MarketDataEventProto) */ {
 public:
  inline MarketDataEventProto() : MarketDataEventProto(nullptr) {}
  ~MarketDataEventProto() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(MarketDataEventProto* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(MarketDataEventProto));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR MarketDataEventProto(::google::protobuf::internal::ConstantInitialized);

  inline MarketDataEventProto(const MarketDataEventProto& from) : MarketDataEventProto(nullptr, from) {}
  inline MarketDataEventProto(MarketDataEventProto&& from) noexcept
      : MarketDataEventProto(nullptr, std::move(from)) {}
  inline MarketDataEventProto& operator=(const MarketDataEventProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline MarketDataEventProto& operator=(MarketDataEventProto&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MarketDataEventProto& default_instance() {
    return *reinterpret_cast<const MarketDataEventProto*>(
        &_MarketDataEventProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(MarketDataEventProto& a, MarketDataEventProto& b) { a.Swap(&b); }
  inline void Swap(MarketDataEventProto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MarketDataEventProto* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MarketDataEventProto* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<MarketDataEventProto>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const MarketDataEventProto& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const MarketDataEventProto& from) { MarketDataEventProto::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(MarketDataEventProto* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "MarketDataEventProto"; }

 protected:
  explicit MarketDataEventProto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  MarketDataEventProto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const MarketDataEventProto& from);
  MarketDataEventProto(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, MarketDataEventProto&& from) noexcept
      : MarketDataEventProto(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSymbolFieldNumber = 2,
    kExchange1FieldNumber = 3,
    kExchange2FieldNumber = 4,
    kBestBidExchangeFieldNumber = 9,
    kBestAskExchangeFieldNumber = 12,
    kSpread12FieldNumber = 5,
    kSpread21FieldNumber = 6,
    kBestBidPriceFieldNumber = 7,
    kBestBidSizeFieldNumber = 8,
    kBestAskPriceFieldNumber = 10,
    kBestAskSizeFieldNumber = 11,
    kImbalance1FieldNumber = 13,
    kImbalance2FieldNumber = 14,
    kAggImbalanceFieldNumber = 15,
    kSimpleMid1FieldNumber = 16,
    kSimpleMid2FieldNumber = 17,
    kSimpleDivergenceFieldNumber = 18,
    kWeightedMid1FieldNumber = 19,
    kWeightedMid2FieldNumber = 20,
    kWeightedDivergenceFieldNumber = 21,
    kSequenceFieldNumber = 1,
  };
  // bytes symbol = 2;
  void clear_symbol() ;
  const std::string& symbol() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_symbol(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_symbol();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_symbol();
  void set_allocated_symbol(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_symbol() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_symbol(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_symbol();

  public:
  // bytes exchange1 = 3;
  void clear_exchange1() ;
  const std::string& exchange1() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_exchange1(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_exchange1();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_exchange1();
  void set_allocated_exchange1(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_exchange1() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_exchange1(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_exchange1();

  public:
  // bytes exchange2 = 4;
  void clear_exchange2() ;
  const std::string& exchange2() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_exchange2(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_exchange2();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_exchange2();
  void set_allocated_exchange2(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_exchange2() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_exchange2(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_exchange2();

  public:
  // bytes bestBidExchange = 9;
  void clear_bestbidexchange() ;
  const std::string& bestbidexchange() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_bestbidexchange(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_bestbidexchange();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_bestbidexchange();
  void set_allocated_bestbidexchange(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_bestbidexchange() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_bestbidexchange(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_bestbidexchange();

  public:
  // bytes bestAskExchange = 12;
  void clear_bestaskexchange() ;
  const std::string& bestaskexchange() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_bestaskexchange(Arg_&& arg, Args_... args);
  std::string* PROTOBUF_NONNULL mutable_bestaskexchange();
  [[nodiscard]] std::string* PROTOBUF_NULLABLE release_bestaskexchange();
  void set_allocated_bestaskexchange(std::string* PROTOBUF_NULLABLE value);

  private:
  const std::string& _internal_bestaskexchange() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_bestaskexchange(const std::string& value);
  std::string* PROTOBUF_NONNULL _internal_mutable_bestaskexchange();

  public:
  // double spread12 = 5;
  void clear_spread12() ;
  double spread12() const;
  void set_spread12(double value);

  private:
  double _internal_spread12() const;
  void _internal_set_spread12(double value);

  public:
  // double spread21 = 6;
  void clear_spread21() ;
  double spread21() const;
  void set_spread21(double value);

  private:
  double _internal_spread21() const;
  void _internal_set_spread21(double value);

  public:
  // double bestBidPrice = 7;
  void clear_bestbidprice() ;
  double bestbidprice() const;
  void set_bestbidprice(double value);

  private:
  double _internal_bestbidprice() const;
  void _internal_set_bestbidprice(double value);

  public:
  // double bestBidSize = 8;
  void clear_bestbidsize() ;
  double bestbidsize() const;
  void set_bestbidsize(double value);

  private:
  double _internal_bestbidsize() const;
  void _internal_set_bestbidsize(double value);

  public:
  // double bestAskPrice = 10;
  void clear_bestaskprice() ;
  double bestaskprice() const;
  void set_bestaskprice(double value);

  private:
  double _internal_bestaskprice() const;
  void _internal_set_bestaskprice(double value);

  public:
  // double bestAskSize = 11;
  void clear_bestasksize() ;
  double bestasksize() const;
  void set_bestasksize(double value);

  private:
  double _internal_bestasksize() const;
  void _internal_set_bestasksize(double value);

  public:
  // double imbalance1 = 13;
  void clear_imbalance1() ;
  double imbalance1() const;
  void set_imbalance1(double value);

  private:
  double _internal_imbalance1() const;
  void _internal_set_imbalance1(double value);

  public:
  // double imbalance2 = 14;
  void clear_imbalance2() ;
  double imbalance2() const;
  void set_imbalance2(double value);

  private:
  double _internal_imbalance2() const;
  void _internal_set_imbalance2(double value);

  public:
  // double aggImbalance = 15;
  void clear_aggimbalance() ;
  double aggimbalance() const;
  void set_aggimbalance(double value);

  private:
  double _internal_aggimbalance() const;
  void _internal_set_aggimbalance(double value);

  public:
  // double simpleMid1 = 16;
  void clear_simplemid1() ;
  double simplemid1() const;
  void set_simplemid1(double value);

  private:
  double _internal_simplemid1() const;
  void _internal_set_simplemid1(double value);

  public:
  // double simpleMid2 = 17;
  void clear_simplemid2() ;
  double simplemid2() const;
  void set_simplemid2(double value);

  private:
  double _internal_simplemid2() const;
  void _internal_set_simplemid2(double value);

  public:
  // double simpleDivergence = 18;
  void clear_simpledivergence() ;
  double simpledivergence() const;
  void set_simpledivergence(double value);

  private:
  double _internal_simpledivergence() const;
  void _internal_set_simpledivergence(double value);

  public:
  // double weightedMid1 = 19;
  void clear_weightedmid1() ;
  double weightedmid1() const;
  void set_weightedmid1(double value);

  private:
  double _internal_weightedmid1() const;
  void _internal_set_weightedmid1(double value);

  public:
  // double weightedMid2 = 20;
  void clear_weightedmid2() ;
  double weightedmid2() const;
  void set_weightedmid2(double value);

  private:
  double _internal_weightedmid2() const;
  void _internal_set_weightedmid2(double value);

  public:
  // double weightedDivergence = 21;
  void clear_weighteddivergence() ;
  double weighteddivergence() const;
  void set_weighteddivergence(double value);

  private:
  double _internal_weighteddivergence() const;
  void _internal_set_weighteddivergence(double value);

  public:
  // fixed32 sequence = 1;
  void clear_sequence() ;
  ::uint32_t sequence() const;
  void set_sequence(::uint32_t value);

  private:
  ::uint32_t _internal_sequence() const;
  void _internal_set_sequence(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:MarketDataEventProto)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<5, 21,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const MarketDataEventProto& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr symbol_;
    ::google::protobuf::internal::ArenaStringPtr exchange1_;
    ::google::protobuf::internal::ArenaStringPtr exchange2_;
    ::google::protobuf::internal::ArenaStringPtr bestbidexchange_;
    ::google::protobuf::internal::ArenaStringPtr bestaskexchange_;
    double spread12_;
    double spread21_;
    double bestbidprice_;
    double bestbidsize_;
    double bestaskprice_;
    double bestasksize_;
    double imbalance1_;
    double imbalance2_;
    double aggimbalance_;
    double simplemid1_;
    double simplemid2_;
    double simpledivergence_;
    double weightedmid1_;
    double weightedmid2_;
    double weighteddivergence_;
    ::uint32_t sequence_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_market_5fdata_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull MarketDataEventProto_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// MarketDataEventProto

// fixed32 sequence = 1;
inline void MarketDataEventProto::clear_sequence() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequence_ = 0u;
  _impl_._has_bits_[0] &= ~0x00100000u;
}
inline ::uint32_t MarketDataEventProto::sequence() const {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.sequence)
  return _internal_sequence();
}
inline void MarketDataEventProto::set_sequence(::uint32_t value) {
  _internal_set_sequence(value);
  _impl_._has_bits_[0] |= 0x00100000u;
  // @@protoc_insertion_point(field_set:MarketDataEventProto.sequence)
}
inline ::uint32_t MarketDataEventProto::_internal_sequence() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sequence_;
}
inline void MarketDataEventProto::_internal_set_sequence(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sequence_ = value;
}

// bytes symbol = 2;
inline void MarketDataEventProto::clear_symbol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.symbol_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& MarketDataEventProto::symbol() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.symbol)
  return _internal_symbol();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MarketDataEventProto::set_symbol(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.symbol_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:MarketDataEventProto.symbol)
}
inline std::string* PROTOBUF_NONNULL MarketDataEventProto::mutable_symbol()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_symbol();
  // @@protoc_insertion_point(field_mutable:MarketDataEventProto.symbol)
  return _s;
}
inline const std::string& MarketDataEventProto::_internal_symbol() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.symbol_.Get();
}
inline void MarketDataEventProto::_internal_set_symbol(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.symbol_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL MarketDataEventProto::_internal_mutable_symbol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.symbol_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE MarketDataEventProto::release_symbol() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:MarketDataEventProto.symbol)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.symbol_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.symbol_.Set("", GetArena());
  }
  return released;
}
inline void MarketDataEventProto::set_allocated_symbol(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.symbol_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.symbol_.IsDefault()) {
    _impl_.symbol_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:MarketDataEventProto.symbol)
}

// bytes exchange1 = 3;
inline void MarketDataEventProto::clear_exchange1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exchange1_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& MarketDataEventProto::exchange1() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.exchange1)
  return _internal_exchange1();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MarketDataEventProto::set_exchange1(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.exchange1_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:MarketDataEventProto.exchange1)
}
inline std::string* PROTOBUF_NONNULL MarketDataEventProto::mutable_exchange1()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_exchange1();
  // @@protoc_insertion_point(field_mutable:MarketDataEventProto.exchange1)
  return _s;
}
inline const std::string& MarketDataEventProto::_internal_exchange1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.exchange1_.Get();
}
inline void MarketDataEventProto::_internal_set_exchange1(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.exchange1_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL MarketDataEventProto::_internal_mutable_exchange1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.exchange1_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE MarketDataEventProto::release_exchange1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:MarketDataEventProto.exchange1)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.exchange1_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.exchange1_.Set("", GetArena());
  }
  return released;
}
inline void MarketDataEventProto::set_allocated_exchange1(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.exchange1_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.exchange1_.IsDefault()) {
    _impl_.exchange1_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:MarketDataEventProto.exchange1)
}

// bytes exchange2 = 4;
inline void MarketDataEventProto::clear_exchange2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exchange2_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& MarketDataEventProto::exchange2() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.exchange2)
  return _internal_exchange2();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MarketDataEventProto::set_exchange2(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.exchange2_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:MarketDataEventProto.exchange2)
}
inline std::string* PROTOBUF_NONNULL MarketDataEventProto::mutable_exchange2()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_exchange2();
  // @@protoc_insertion_point(field_mutable:MarketDataEventProto.exchange2)
  return _s;
}
inline const std::string& MarketDataEventProto::_internal_exchange2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.exchange2_.Get();
}
inline void MarketDataEventProto::_internal_set_exchange2(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.exchange2_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL MarketDataEventProto::_internal_mutable_exchange2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.exchange2_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE MarketDataEventProto::release_exchange2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:MarketDataEventProto.exchange2)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* released = _impl_.exchange2_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.exchange2_.Set("", GetArena());
  }
  return released;
}
inline void MarketDataEventProto::set_allocated_exchange2(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.exchange2_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.exchange2_.IsDefault()) {
    _impl_.exchange2_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:MarketDataEventProto.exchange2)
}

// double spread12 = 5;
inline void MarketDataEventProto::clear_spread12() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.spread12_ = 0;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline double MarketDataEventProto::spread12() const {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.spread12)
  return _internal_spread12();
}
inline void MarketDataEventProto::set_spread12(double value) {
  _internal_set_spread12(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:MarketDataEventProto.spread12)
}
inline double MarketDataEventProto::_internal_spread12() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.spread12_;
}
inline void MarketDataEventProto::_internal_set_spread12(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.spread12_ = value;
}

// double spread21 = 6;
inline void MarketDataEventProto::clear_spread21() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.spread21_ = 0;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline double MarketDataEventProto::spread21() const {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.spread21)
  return _internal_spread21();
}
inline void MarketDataEventProto::set_spread21(double value) {
  _internal_set_spread21(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:MarketDataEventProto.spread21)
}
inline double MarketDataEventProto::_internal_spread21() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.spread21_;
}
inline void MarketDataEventProto::_internal_set_spread21(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.spread21_ = value;
}

// double bestBidPrice = 7;
inline void MarketDataEventProto::clear_bestbidprice() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bestbidprice_ = 0;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline double MarketDataEventProto::bestbidprice() const {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.bestBidPrice)
  return _internal_bestbidprice();
}
inline void MarketDataEventProto::set_bestbidprice(double value) {
  _internal_set_bestbidprice(value);
  _impl_._has_bits_[0] |= 0x00000080u;
  // @@protoc_insertion_point(field_set:MarketDataEventProto.bestBidPrice)
}
inline double MarketDataEventProto::_internal_bestbidprice() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bestbidprice_;
}
inline void MarketDataEventProto::_internal_set_bestbidprice(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bestbidprice_ = value;
}

// double bestBidSize = 8;
inline void MarketDataEventProto::clear_bestbidsize() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bestbidsize_ = 0;
  _impl_._has_bits_[0] &= ~0x00000100u;
}
inline double MarketDataEventProto::bestbidsize() const {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.bestBidSize)
  return _internal_bestbidsize();
}
inline void MarketDataEventProto::set_bestbidsize(double value) {
  _internal_set_bestbidsize(value);
  _impl_._has_bits_[0] |= 0x00000100u;
  // @@protoc_insertion_point(field_set:MarketDataEventProto.bestBidSize)
}
inline double MarketDataEventProto::_internal_bestbidsize() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bestbidsize_;
}
inline void MarketDataEventProto::_internal_set_bestbidsize(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bestbidsize_ = value;
}

// bytes bestBidExchange = 9;
inline void MarketDataEventProto::clear_bestbidexchange() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bestbidexchange_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& MarketDataEventProto::bestbidexchange() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.bestBidExchange)
  return _internal_bestbidexchange();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MarketDataEventProto::set_bestbidexchange(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.bestbidexchange_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:MarketDataEventProto.bestBidExchange)
}
inline std::string* PROTOBUF_NONNULL MarketDataEventProto::mutable_bestbidexchange()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_bestbidexchange();
  // @@protoc_insertion_point(field_mutable:MarketDataEventProto.bestBidExchange)
  return _s;
}
inline const std::string& MarketDataEventProto::_internal_bestbidexchange() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bestbidexchange_.Get();
}
inline void MarketDataEventProto::_internal_set_bestbidexchange(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.bestbidexchange_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL MarketDataEventProto::_internal_mutable_bestbidexchange() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.bestbidexchange_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE MarketDataEventProto::release_bestbidexchange() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:MarketDataEventProto.bestBidExchange)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.bestbidexchange_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.bestbidexchange_.Set("", GetArena());
  }
  return released;
}
inline void MarketDataEventProto::set_allocated_bestbidexchange(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.bestbidexchange_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.bestbidexchange_.IsDefault()) {
    _impl_.bestbidexchange_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:MarketDataEventProto.bestBidExchange)
}

// double bestAskPrice = 10;
inline void MarketDataEventProto::clear_bestaskprice() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bestaskprice_ = 0;
  _impl_._has_bits_[0] &= ~0x00000200u;
}
inline double MarketDataEventProto::bestaskprice() const {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.bestAskPrice)
  return _internal_bestaskprice();
}
inline void MarketDataEventProto::set_bestaskprice(double value) {
  _internal_set_bestaskprice(value);
  _impl_._has_bits_[0] |= 0x00000200u;
  // @@protoc_insertion_point(field_set:MarketDataEventProto.bestAskPrice)
}
inline double MarketDataEventProto::_internal_bestaskprice() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bestaskprice_;
}
inline void MarketDataEventProto::_internal_set_bestaskprice(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bestaskprice_ = value;
}

// double bestAskSize = 11;
inline void MarketDataEventProto::clear_bestasksize() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bestasksize_ = 0;
  _impl_._has_bits_[0] &= ~0x00000400u;
}
inline double MarketDataEventProto::bestasksize() const {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.bestAskSize)
  return _internal_bestasksize();
}
inline void MarketDataEventProto::set_bestasksize(double value) {
  _internal_set_bestasksize(value);
  _impl_._has_bits_[0] |= 0x00000400u;
  // @@protoc_insertion_point(field_set:MarketDataEventProto.bestAskSize)
}
inline double MarketDataEventProto::_internal_bestasksize() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bestasksize_;
}
inline void MarketDataEventProto::_internal_set_bestasksize(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bestasksize_ = value;
}

// bytes bestAskExchange = 12;
inline void MarketDataEventProto::clear_bestaskexchange() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bestaskexchange_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline const std::string& MarketDataEventProto::bestaskexchange() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.bestAskExchange)
  return _internal_bestaskexchange();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void MarketDataEventProto::set_bestaskexchange(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.bestaskexchange_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:MarketDataEventProto.bestAskExchange)
}
inline std::string* PROTOBUF_NONNULL MarketDataEventProto::mutable_bestaskexchange()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_bestaskexchange();
  // @@protoc_insertion_point(field_mutable:MarketDataEventProto.bestAskExchange)
  return _s;
}
inline const std::string& MarketDataEventProto::_internal_bestaskexchange() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bestaskexchange_.Get();
}
inline void MarketDataEventProto::_internal_set_bestaskexchange(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.bestaskexchange_.Set(value, GetArena());
}
inline std::string* PROTOBUF_NONNULL MarketDataEventProto::_internal_mutable_bestaskexchange() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000010u;
  return _impl_.bestaskexchange_.Mutable( GetArena());
}
inline std::string* PROTOBUF_NULLABLE MarketDataEventProto::release_bestaskexchange() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:MarketDataEventProto.bestAskExchange)
  if ((_impl_._has_bits_[0] & 0x00000010u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000010u;
  auto* released = _impl_.bestaskexchange_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.bestaskexchange_.Set("", GetArena());
  }
  return released;
}
inline void MarketDataEventProto::set_allocated_bestaskexchange(std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000010u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000010u;
  }
  _impl_.bestaskexchange_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.bestaskexchange_.IsDefault()) {
    _impl_.bestaskexchange_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:MarketDataEventProto.bestAskExchange)
}

// double imbalance1 = 13;
inline void MarketDataEventProto::clear_imbalance1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.imbalance1_ = 0;
  _impl_._has_bits_[0] &= ~0x00000800u;
}
inline double MarketDataEventProto::imbalance1() const {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.imbalance1)
  return _internal_imbalance1();
}
inline void MarketDataEventProto::set_imbalance1(double value) {
  _internal_set_imbalance1(value);
  _impl_._has_bits_[0] |= 0x00000800u;
  // @@protoc_insertion_point(field_set:MarketDataEventProto.imbalance1)
}
inline double MarketDataEventProto::_internal_imbalance1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.imbalance1_;
}
inline void MarketDataEventProto::_internal_set_imbalance1(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.imbalance1_ = value;
}

// double imbalance2 = 14;
inline void MarketDataEventProto::clear_imbalance2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.imbalance2_ = 0;
  _impl_._has_bits_[0] &= ~0x00001000u;
}
inline double MarketDataEventProto::imbalance2() const {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.imbalance2)
  return _internal_imbalance2();
}
inline void MarketDataEventProto::set_imbalance2(double value) {
  _internal_set_imbalance2(value);
  _impl_._has_bits_[0] |= 0x00001000u;
  // @@protoc_insertion_point(field_set:MarketDataEventProto.imbalance2)
}
inline double MarketDataEventProto::_internal_imbalance2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.imbalance2_;
}
inline void MarketDataEventProto::_internal_set_imbalance2(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.imbalance2_ = value;
}

// double aggImbalance = 15;
inline void MarketDataEventProto::clear_aggimbalance() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.aggimbalance_ = 0;
  _impl_._has_bits_[0] &= ~0x00002000u;
}
inline double MarketDataEventProto::aggimbalance() const {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.aggImbalance)
  return _internal_aggimbalance();
}
inline void MarketDataEventProto::set_aggimbalance(double value) {
  _internal_set_aggimbalance(value);
  _impl_._has_bits_[0] |= 0x00002000u;
  // @@protoc_insertion_point(field_set:MarketDataEventProto.aggImbalance)
}
inline double MarketDataEventProto::_internal_aggimbalance() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.aggimbalance_;
}
inline void MarketDataEventProto::_internal_set_aggimbalance(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.aggimbalance_ = value;
}

// double simpleMid1 = 16;
inline void MarketDataEventProto::clear_simplemid1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.simplemid1_ = 0;
  _impl_._has_bits_[0] &= ~0x00004000u;
}
inline double MarketDataEventProto::simplemid1() const {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.simpleMid1)
  return _internal_simplemid1();
}
inline void MarketDataEventProto::set_simplemid1(double value) {
  _internal_set_simplemid1(value);
  _impl_._has_bits_[0] |= 0x00004000u;
  // @@protoc_insertion_point(field_set:MarketDataEventProto.simpleMid1)
}
inline double MarketDataEventProto::_internal_simplemid1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.simplemid1_;
}
inline void MarketDataEventProto::_internal_set_simplemid1(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.simplemid1_ = value;
}

// double simpleMid2 = 17;
inline void MarketDataEventProto::clear_simplemid2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.simplemid2_ = 0;
  _impl_._has_bits_[0] &= ~0x00008000u;
}
inline double MarketDataEventProto::simplemid2() const {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.simpleMid2)
  return _internal_simplemid2();
}
inline void MarketDataEventProto::set_simplemid2(double value) {
  _internal_set_simplemid2(value);
  _impl_._has_bits_[0] |= 0x00008000u;
  // @@protoc_insertion_point(field_set:MarketDataEventProto.simpleMid2)
}
inline double MarketDataEventProto::_internal_simplemid2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.simplemid2_;
}
inline void MarketDataEventProto::_internal_set_simplemid2(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.simplemid2_ = value;
}

// double simpleDivergence = 18;
inline void MarketDataEventProto::clear_simpledivergence() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.simpledivergence_ = 0;
  _impl_._has_bits_[0] &= ~0x00010000u;
}
inline double MarketDataEventProto::simpledivergence() const {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.simpleDivergence)
  return _internal_simpledivergence();
}
inline void MarketDataEventProto::set_simpledivergence(double value) {
  _internal_set_simpledivergence(value);
  _impl_._has_bits_[0] |= 0x00010000u;
  // @@protoc_insertion_point(field_set:MarketDataEventProto.simpleDivergence)
}
inline double MarketDataEventProto::_internal_simpledivergence() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.simpledivergence_;
}
inline void MarketDataEventProto::_internal_set_simpledivergence(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.simpledivergence_ = value;
}

// double weightedMid1 = 19;
inline void MarketDataEventProto::clear_weightedmid1() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.weightedmid1_ = 0;
  _impl_._has_bits_[0] &= ~0x00020000u;
}
inline double MarketDataEventProto::weightedmid1() const {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.weightedMid1)
  return _internal_weightedmid1();
}
inline void MarketDataEventProto::set_weightedmid1(double value) {
  _internal_set_weightedmid1(value);
  _impl_._has_bits_[0] |= 0x00020000u;
  // @@protoc_insertion_point(field_set:MarketDataEventProto.weightedMid1)
}
inline double MarketDataEventProto::_internal_weightedmid1() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.weightedmid1_;
}
inline void MarketDataEventProto::_internal_set_weightedmid1(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.weightedmid1_ = value;
}

// double weightedMid2 = 20;
inline void MarketDataEventProto::clear_weightedmid2() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.weightedmid2_ = 0;
  _impl_._has_bits_[0] &= ~0x00040000u;
}
inline double MarketDataEventProto::weightedmid2() const {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.weightedMid2)
  return _internal_weightedmid2();
}
inline void MarketDataEventProto::set_weightedmid2(double value) {
  _internal_set_weightedmid2(value);
  _impl_._has_bits_[0] |= 0x00040000u;
  // @@protoc_insertion_point(field_set:MarketDataEventProto.weightedMid2)
}
inline double MarketDataEventProto::_internal_weightedmid2() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.weightedmid2_;
}
inline void MarketDataEventProto::_internal_set_weightedmid2(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.weightedmid2_ = value;
}

// double weightedDivergence = 21;
inline void MarketDataEventProto::clear_weighteddivergence() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.weighteddivergence_ = 0;
  _impl_._has_bits_[0] &= ~0x00080000u;
}
inline double MarketDataEventProto::weighteddivergence() const {
  // @@protoc_insertion_point(field_get:MarketDataEventProto.weightedDivergence)
  return _internal_weighteddivergence();
}
inline void MarketDataEventProto::set_weighteddivergence(double value) {
  _internal_set_weighteddivergence(value);
  _impl_._has_bits_[0] |= 0x00080000u;
  // @@protoc_insertion_point(field_set:MarketDataEventProto.weightedDivergence)
}
inline double MarketDataEventProto::_internal_weighteddivergence() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.weighteddivergence_;
}
inline void MarketDataEventProto::_internal_set_weighteddivergence(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.weighteddivergence_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // market_5fdata_2eproto_2epb_2eh
