// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: market_data.proto
// Protobuf C++ Version: 6.30.2

#include "market_data.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr MarketDataEventProto::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        symbol_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        exchange1_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        exchange2_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        bestbidexchange_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        bestaskexchange_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        spread12_{0},
        spread21_{0},
        bestbidprice_{0},
        bestbidsize_{0},
        bestaskprice_{0},
        bestasksize_{0},
        imbalance1_{0},
        imbalance2_{0},
        aggimbalance_{0},
        simplemid1_{0},
        simplemid2_{0},
        simpledivergence_{0},
        weightedmid1_{0},
        weightedmid2_{0},
        weighteddivergence_{0},
        sequence_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR MarketDataEventProto::MarketDataEventProto(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(MarketDataEventProto_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MarketDataEventProtoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MarketDataEventProtoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MarketDataEventProtoDefaultTypeInternal() {}
  union {
    MarketDataEventProto _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MarketDataEventProtoDefaultTypeInternal _MarketDataEventProto_default_instance_;
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_market_5fdata_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_market_5fdata_2eproto = nullptr;
const ::uint32_t
    TableStruct_market_5fdata_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.sequence_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.symbol_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.exchange1_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.exchange2_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.spread12_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.spread21_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.bestbidprice_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.bestbidsize_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.bestbidexchange_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.bestaskprice_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.bestasksize_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.bestaskexchange_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.imbalance1_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.imbalance2_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.aggimbalance_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.simplemid1_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.simplemid2_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.simpledivergence_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.weightedmid1_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.weightedmid2_),
        PROTOBUF_FIELD_OFFSET(::MarketDataEventProto, _impl_.weighteddivergence_),
        20,
        0,
        1,
        2,
        5,
        6,
        7,
        8,
        3,
        9,
        10,
        4,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 29, -1, sizeof(::MarketDataEventProto)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_MarketDataEventProto_default_instance_._instance,
};
const char descriptor_table_protodef_market_5fdata_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\021market_data.proto\"\322\003\n\024MarketDataEventP"
    "roto\022\020\n\010sequence\030\001 \001(\007\022\016\n\006symbol\030\002 \001(\014\022\021"
    "\n\texchange1\030\003 \001(\014\022\021\n\texchange2\030\004 \001(\014\022\020\n\010"
    "spread12\030\005 \001(\001\022\020\n\010spread21\030\006 \001(\001\022\024\n\014best"
    "BidPrice\030\007 \001(\001\022\023\n\013bestBidSize\030\010 \001(\001\022\027\n\017b"
    "estBidExchange\030\t \001(\014\022\024\n\014bestAskPrice\030\n \001"
    "(\001\022\023\n\013bestAskSize\030\013 \001(\001\022\027\n\017bestAskExchan"
    "ge\030\014 \001(\014\022\022\n\nimbalance1\030\r \001(\001\022\022\n\nimbalanc"
    "e2\030\016 \001(\001\022\024\n\014aggImbalance\030\017 \001(\001\022\022\n\nsimple"
    "Mid1\030\020 \001(\001\022\022\n\nsimpleMid2\030\021 \001(\001\022\030\n\020simple"
    "Divergence\030\022 \001(\001\022\024\n\014weightedMid1\030\023 \001(\001\022\024"
    "\n\014weightedMid2\030\024 \001(\001\022\032\n\022weightedDivergen"
    "ce\030\025 \001(\001b\006proto3"
};
static ::absl::once_flag descriptor_table_market_5fdata_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_market_5fdata_2eproto = {
    false,
    false,
    496,
    descriptor_table_protodef_market_5fdata_2eproto,
    "market_data.proto",
    &descriptor_table_market_5fdata_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_market_5fdata_2eproto::offsets,
    file_level_enum_descriptors_market_5fdata_2eproto,
    file_level_service_descriptors_market_5fdata_2eproto,
};
// ===================================================================

class MarketDataEventProto::_Internal {
 public:
  using HasBits =
      decltype(std::declval<MarketDataEventProto>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_._has_bits_);
};

MarketDataEventProto::MarketDataEventProto(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MarketDataEventProto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MarketDataEventProto)
}
PROTOBUF_NDEBUG_INLINE MarketDataEventProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::MarketDataEventProto& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        symbol_(arena, from.symbol_),
        exchange1_(arena, from.exchange1_),
        exchange2_(arena, from.exchange2_),
        bestbidexchange_(arena, from.bestbidexchange_),
        bestaskexchange_(arena, from.bestaskexchange_) {}

MarketDataEventProto::MarketDataEventProto(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const MarketDataEventProto& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, MarketDataEventProto_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  MarketDataEventProto* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, spread12_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, spread12_),
           offsetof(Impl_, sequence_) -
               offsetof(Impl_, spread12_) +
               sizeof(Impl_::sequence_));

  // @@protoc_insertion_point(copy_constructor:MarketDataEventProto)
}
PROTOBUF_NDEBUG_INLINE MarketDataEventProto::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        symbol_(arena),
        exchange1_(arena),
        exchange2_(arena),
        bestbidexchange_(arena),
        bestaskexchange_(arena) {}

inline void MarketDataEventProto::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, spread12_),
           0,
           offsetof(Impl_, sequence_) -
               offsetof(Impl_, spread12_) +
               sizeof(Impl_::sequence_));
}
MarketDataEventProto::~MarketDataEventProto() {
  // @@protoc_insertion_point(destructor:MarketDataEventProto)
  SharedDtor(*this);
}
inline void MarketDataEventProto::SharedDtor(MessageLite& self) {
  MarketDataEventProto& this_ = static_cast<MarketDataEventProto&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.symbol_.Destroy();
  this_._impl_.exchange1_.Destroy();
  this_._impl_.exchange2_.Destroy();
  this_._impl_.bestbidexchange_.Destroy();
  this_._impl_.bestaskexchange_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL MarketDataEventProto::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) MarketDataEventProto(arena);
}
constexpr auto MarketDataEventProto::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(MarketDataEventProto),
                                            alignof(MarketDataEventProto));
}
constexpr auto MarketDataEventProto::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_MarketDataEventProto_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &MarketDataEventProto::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<MarketDataEventProto>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &MarketDataEventProto::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<MarketDataEventProto>(), &MarketDataEventProto::ByteSizeLong,
              &MarketDataEventProto::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_._cached_size_),
          false,
      },
      &MarketDataEventProto::kDescriptorMethods,
      &descriptor_table_market_5fdata_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull MarketDataEventProto_class_data_ =
        MarketDataEventProto::InternalGenerateClassData_();

const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL MarketDataEventProto::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&MarketDataEventProto_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(MarketDataEventProto_class_data_.tc_table);
  return MarketDataEventProto_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<5, 21, 0, 0, 2>
MarketDataEventProto::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_._has_bits_),
    0, // no _extensions_
    21, 248,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4292870144,  // skipmap
    offsetof(decltype(_table_), field_entries),
    21,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    MarketDataEventProto_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::MarketDataEventProto>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // fixed32 sequence = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 20, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.sequence_)}},
    // bytes symbol = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.symbol_)}},
    // bytes exchange1 = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 1, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.exchange1_)}},
    // bytes exchange2 = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 2, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.exchange2_)}},
    // double spread12 = 5;
    {::_pbi::TcParser::FastF64S1,
     {41, 5, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.spread12_)}},
    // double spread21 = 6;
    {::_pbi::TcParser::FastF64S1,
     {49, 6, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.spread21_)}},
    // double bestBidPrice = 7;
    {::_pbi::TcParser::FastF64S1,
     {57, 7, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.bestbidprice_)}},
    // double bestBidSize = 8;
    {::_pbi::TcParser::FastF64S1,
     {65, 8, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.bestbidsize_)}},
    // bytes bestBidExchange = 9;
    {::_pbi::TcParser::FastBS1,
     {74, 3, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.bestbidexchange_)}},
    // double bestAskPrice = 10;
    {::_pbi::TcParser::FastF64S1,
     {81, 9, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.bestaskprice_)}},
    // double bestAskSize = 11;
    {::_pbi::TcParser::FastF64S1,
     {89, 10, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.bestasksize_)}},
    // bytes bestAskExchange = 12;
    {::_pbi::TcParser::FastBS1,
     {98, 4, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.bestaskexchange_)}},
    // double imbalance1 = 13;
    {::_pbi::TcParser::FastF64S1,
     {105, 11, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.imbalance1_)}},
    // double imbalance2 = 14;
    {::_pbi::TcParser::FastF64S1,
     {113, 12, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.imbalance2_)}},
    // double aggImbalance = 15;
    {::_pbi::TcParser::FastF64S1,
     {121, 13, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.aggimbalance_)}},
    // double simpleMid1 = 16;
    {::_pbi::TcParser::FastF64S2,
     {385, 14, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.simplemid1_)}},
    // double simpleMid2 = 17;
    {::_pbi::TcParser::FastF64S2,
     {393, 15, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.simplemid2_)}},
    // double simpleDivergence = 18;
    {::_pbi::TcParser::FastF64S2,
     {401, 16, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.simpledivergence_)}},
    // double weightedMid1 = 19;
    {::_pbi::TcParser::FastF64S2,
     {409, 17, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.weightedmid1_)}},
    // double weightedMid2 = 20;
    {::_pbi::TcParser::FastF64S2,
     {417, 18, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.weightedmid2_)}},
    // double weightedDivergence = 21;
    {::_pbi::TcParser::FastF64S2,
     {425, 19, 0, PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.weighteddivergence_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // fixed32 sequence = 1;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.sequence_), _Internal::kHasBitsOffset + 20, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFixed32)},
    // bytes symbol = 2;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.symbol_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes exchange1 = 3;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.exchange1_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes exchange2 = 4;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.exchange2_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // double spread12 = 5;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.spread12_), _Internal::kHasBitsOffset + 5, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double spread21 = 6;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.spread21_), _Internal::kHasBitsOffset + 6, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double bestBidPrice = 7;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.bestbidprice_), _Internal::kHasBitsOffset + 7, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double bestBidSize = 8;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.bestbidsize_), _Internal::kHasBitsOffset + 8, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // bytes bestBidExchange = 9;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.bestbidexchange_), _Internal::kHasBitsOffset + 3, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // double bestAskPrice = 10;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.bestaskprice_), _Internal::kHasBitsOffset + 9, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double bestAskSize = 11;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.bestasksize_), _Internal::kHasBitsOffset + 10, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // bytes bestAskExchange = 12;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.bestaskexchange_), _Internal::kHasBitsOffset + 4, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // double imbalance1 = 13;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.imbalance1_), _Internal::kHasBitsOffset + 11, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double imbalance2 = 14;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.imbalance2_), _Internal::kHasBitsOffset + 12, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double aggImbalance = 15;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.aggimbalance_), _Internal::kHasBitsOffset + 13, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double simpleMid1 = 16;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.simplemid1_), _Internal::kHasBitsOffset + 14, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double simpleMid2 = 17;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.simplemid2_), _Internal::kHasBitsOffset + 15, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double simpleDivergence = 18;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.simpledivergence_), _Internal::kHasBitsOffset + 16, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double weightedMid1 = 19;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.weightedmid1_), _Internal::kHasBitsOffset + 17, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double weightedMid2 = 20;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.weightedmid2_), _Internal::kHasBitsOffset + 18, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double weightedDivergence = 21;
    {PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.weighteddivergence_), _Internal::kHasBitsOffset + 19, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void MarketDataEventProto::Clear() {
// @@protoc_insertion_point(message_clear_start:MarketDataEventProto)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.symbol_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.exchange1_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _impl_.exchange2_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      _impl_.bestbidexchange_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      _impl_.bestaskexchange_.ClearNonDefaultToEmpty();
    }
  }
  if ((cached_has_bits & 0x000000e0u) != 0) {
    ::memset(&_impl_.spread12_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.bestbidprice_) -
        reinterpret_cast<char*>(&_impl_.spread12_)) + sizeof(_impl_.bestbidprice_));
  }
  if ((cached_has_bits & 0x0000ff00u) != 0) {
    ::memset(&_impl_.bestbidsize_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.simplemid2_) -
        reinterpret_cast<char*>(&_impl_.bestbidsize_)) + sizeof(_impl_.simplemid2_));
  }
  if ((cached_has_bits & 0x001f0000u) != 0) {
    ::memset(&_impl_.simpledivergence_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.sequence_) -
        reinterpret_cast<char*>(&_impl_.simpledivergence_)) + sizeof(_impl_.sequence_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL MarketDataEventProto::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const MarketDataEventProto& this_ = static_cast<const MarketDataEventProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL MarketDataEventProto::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const MarketDataEventProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:MarketDataEventProto)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // fixed32 sequence = 1;
  if ((this_._impl_._has_bits_[0] & 0x00100000u) != 0) {
    if (this_._internal_sequence() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFixed32ToArray(
          1, this_._internal_sequence(), target);
    }
  }

  // bytes symbol = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (!this_._internal_symbol().empty()) {
      const std::string& _s = this_._internal_symbol();
      target = stream->WriteBytesMaybeAliased(2, _s, target);
    }
  }

  // bytes exchange1 = 3;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (!this_._internal_exchange1().empty()) {
      const std::string& _s = this_._internal_exchange1();
      target = stream->WriteBytesMaybeAliased(3, _s, target);
    }
  }

  // bytes exchange2 = 4;
  if ((this_._impl_._has_bits_[0] & 0x00000004u) != 0) {
    if (!this_._internal_exchange2().empty()) {
      const std::string& _s = this_._internal_exchange2();
      target = stream->WriteBytesMaybeAliased(4, _s, target);
    }
  }

  // double spread12 = 5;
  if ((this_._impl_._has_bits_[0] & 0x00000020u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_spread12()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          5, this_._internal_spread12(), target);
    }
  }

  // double spread21 = 6;
  if ((this_._impl_._has_bits_[0] & 0x00000040u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_spread21()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          6, this_._internal_spread21(), target);
    }
  }

  // double bestBidPrice = 7;
  if ((this_._impl_._has_bits_[0] & 0x00000080u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_bestbidprice()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          7, this_._internal_bestbidprice(), target);
    }
  }

  // double bestBidSize = 8;
  if ((this_._impl_._has_bits_[0] & 0x00000100u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_bestbidsize()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          8, this_._internal_bestbidsize(), target);
    }
  }

  // bytes bestBidExchange = 9;
  if ((this_._impl_._has_bits_[0] & 0x00000008u) != 0) {
    if (!this_._internal_bestbidexchange().empty()) {
      const std::string& _s = this_._internal_bestbidexchange();
      target = stream->WriteBytesMaybeAliased(9, _s, target);
    }
  }

  // double bestAskPrice = 10;
  if ((this_._impl_._has_bits_[0] & 0x00000200u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_bestaskprice()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          10, this_._internal_bestaskprice(), target);
    }
  }

  // double bestAskSize = 11;
  if ((this_._impl_._has_bits_[0] & 0x00000400u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_bestasksize()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          11, this_._internal_bestasksize(), target);
    }
  }

  // bytes bestAskExchange = 12;
  if ((this_._impl_._has_bits_[0] & 0x00000010u) != 0) {
    if (!this_._internal_bestaskexchange().empty()) {
      const std::string& _s = this_._internal_bestaskexchange();
      target = stream->WriteBytesMaybeAliased(12, _s, target);
    }
  }

  // double imbalance1 = 13;
  if ((this_._impl_._has_bits_[0] & 0x00000800u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_imbalance1()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          13, this_._internal_imbalance1(), target);
    }
  }

  // double imbalance2 = 14;
  if ((this_._impl_._has_bits_[0] & 0x00001000u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_imbalance2()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          14, this_._internal_imbalance2(), target);
    }
  }

  // double aggImbalance = 15;
  if ((this_._impl_._has_bits_[0] & 0x00002000u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_aggimbalance()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          15, this_._internal_aggimbalance(), target);
    }
  }

  // double simpleMid1 = 16;
  if ((this_._impl_._has_bits_[0] & 0x00004000u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_simplemid1()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          16, this_._internal_simplemid1(), target);
    }
  }

  // double simpleMid2 = 17;
  if ((this_._impl_._has_bits_[0] & 0x00008000u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_simplemid2()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          17, this_._internal_simplemid2(), target);
    }
  }

  // double simpleDivergence = 18;
  if ((this_._impl_._has_bits_[0] & 0x00010000u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_simpledivergence()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          18, this_._internal_simpledivergence(), target);
    }
  }

  // double weightedMid1 = 19;
  if ((this_._impl_._has_bits_[0] & 0x00020000u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_weightedmid1()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          19, this_._internal_weightedmid1(), target);
    }
  }

  // double weightedMid2 = 20;
  if ((this_._impl_._has_bits_[0] & 0x00040000u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_weightedmid2()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          20, this_._internal_weightedmid2(), target);
    }
  }

  // double weightedDivergence = 21;
  if ((this_._impl_._has_bits_[0] & 0x00080000u) != 0) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_weighteddivergence()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          21, this_._internal_weighteddivergence(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MarketDataEventProto)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t MarketDataEventProto::ByteSizeLong(const MessageLite& base) {
  const MarketDataEventProto& this_ = static_cast<const MarketDataEventProto&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t MarketDataEventProto::ByteSizeLong() const {
  const MarketDataEventProto& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:MarketDataEventProto)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffu) != 0) {
    // bytes symbol = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!this_._internal_symbol().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_symbol());
      }
    }
    // bytes exchange1 = 3;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!this_._internal_exchange1().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_exchange1());
      }
    }
    // bytes exchange2 = 4;
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (!this_._internal_exchange2().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_exchange2());
      }
    }
    // bytes bestBidExchange = 9;
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (!this_._internal_bestbidexchange().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_bestbidexchange());
      }
    }
    // bytes bestAskExchange = 12;
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (!this_._internal_bestaskexchange().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_bestaskexchange());
      }
    }
    // double spread12 = 5;
    if ((cached_has_bits & 0x00000020u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_spread12()) != 0) {
        total_size += 9;
      }
    }
    // double spread21 = 6;
    if ((cached_has_bits & 0x00000040u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_spread21()) != 0) {
        total_size += 9;
      }
    }
    // double bestBidPrice = 7;
    if ((cached_has_bits & 0x00000080u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_bestbidprice()) != 0) {
        total_size += 9;
      }
    }
  }
  if ((cached_has_bits & 0x0000ff00u) != 0) {
    // double bestBidSize = 8;
    if ((cached_has_bits & 0x00000100u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_bestbidsize()) != 0) {
        total_size += 9;
      }
    }
    // double bestAskPrice = 10;
    if ((cached_has_bits & 0x00000200u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_bestaskprice()) != 0) {
        total_size += 9;
      }
    }
    // double bestAskSize = 11;
    if ((cached_has_bits & 0x00000400u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_bestasksize()) != 0) {
        total_size += 9;
      }
    }
    // double imbalance1 = 13;
    if ((cached_has_bits & 0x00000800u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_imbalance1()) != 0) {
        total_size += 9;
      }
    }
    // double imbalance2 = 14;
    if ((cached_has_bits & 0x00001000u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_imbalance2()) != 0) {
        total_size += 9;
      }
    }
    // double aggImbalance = 15;
    if ((cached_has_bits & 0x00002000u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_aggimbalance()) != 0) {
        total_size += 9;
      }
    }
    // double simpleMid1 = 16;
    if ((cached_has_bits & 0x00004000u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_simplemid1()) != 0) {
        total_size += 10;
      }
    }
    // double simpleMid2 = 17;
    if ((cached_has_bits & 0x00008000u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_simplemid2()) != 0) {
        total_size += 10;
      }
    }
  }
  if ((cached_has_bits & 0x001f0000u) != 0) {
    // double simpleDivergence = 18;
    if ((cached_has_bits & 0x00010000u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_simpledivergence()) != 0) {
        total_size += 10;
      }
    }
    // double weightedMid1 = 19;
    if ((cached_has_bits & 0x00020000u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_weightedmid1()) != 0) {
        total_size += 10;
      }
    }
    // double weightedMid2 = 20;
    if ((cached_has_bits & 0x00040000u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_weightedmid2()) != 0) {
        total_size += 10;
      }
    }
    // double weightedDivergence = 21;
    if ((cached_has_bits & 0x00080000u) != 0) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_weighteddivergence()) != 0) {
        total_size += 10;
      }
    }
    // fixed32 sequence = 1;
    if ((cached_has_bits & 0x00100000u) != 0) {
      if (this_._internal_sequence() != 0) {
        total_size += 5;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void MarketDataEventProto::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MarketDataEventProto*>(&to_msg);
  auto& from = static_cast<const MarketDataEventProto&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MarketDataEventProto)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x000000ffu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (!from._internal_symbol().empty()) {
        _this->_internal_set_symbol(from._internal_symbol());
      } else {
        if (_this->_impl_.symbol_.IsDefault()) {
          _this->_internal_set_symbol("");
        }
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (!from._internal_exchange1().empty()) {
        _this->_internal_set_exchange1(from._internal_exchange1());
      } else {
        if (_this->_impl_.exchange1_.IsDefault()) {
          _this->_internal_set_exchange1("");
        }
      }
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      if (!from._internal_exchange2().empty()) {
        _this->_internal_set_exchange2(from._internal_exchange2());
      } else {
        if (_this->_impl_.exchange2_.IsDefault()) {
          _this->_internal_set_exchange2("");
        }
      }
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      if (!from._internal_bestbidexchange().empty()) {
        _this->_internal_set_bestbidexchange(from._internal_bestbidexchange());
      } else {
        if (_this->_impl_.bestbidexchange_.IsDefault()) {
          _this->_internal_set_bestbidexchange("");
        }
      }
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      if (!from._internal_bestaskexchange().empty()) {
        _this->_internal_set_bestaskexchange(from._internal_bestaskexchange());
      } else {
        if (_this->_impl_.bestaskexchange_.IsDefault()) {
          _this->_internal_set_bestaskexchange("");
        }
      }
    }
    if ((cached_has_bits & 0x00000020u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_spread12()) != 0) {
        _this->_impl_.spread12_ = from._impl_.spread12_;
      }
    }
    if ((cached_has_bits & 0x00000040u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_spread21()) != 0) {
        _this->_impl_.spread21_ = from._impl_.spread21_;
      }
    }
    if ((cached_has_bits & 0x00000080u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_bestbidprice()) != 0) {
        _this->_impl_.bestbidprice_ = from._impl_.bestbidprice_;
      }
    }
  }
  if ((cached_has_bits & 0x0000ff00u) != 0) {
    if ((cached_has_bits & 0x00000100u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_bestbidsize()) != 0) {
        _this->_impl_.bestbidsize_ = from._impl_.bestbidsize_;
      }
    }
    if ((cached_has_bits & 0x00000200u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_bestaskprice()) != 0) {
        _this->_impl_.bestaskprice_ = from._impl_.bestaskprice_;
      }
    }
    if ((cached_has_bits & 0x00000400u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_bestasksize()) != 0) {
        _this->_impl_.bestasksize_ = from._impl_.bestasksize_;
      }
    }
    if ((cached_has_bits & 0x00000800u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_imbalance1()) != 0) {
        _this->_impl_.imbalance1_ = from._impl_.imbalance1_;
      }
    }
    if ((cached_has_bits & 0x00001000u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_imbalance2()) != 0) {
        _this->_impl_.imbalance2_ = from._impl_.imbalance2_;
      }
    }
    if ((cached_has_bits & 0x00002000u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_aggimbalance()) != 0) {
        _this->_impl_.aggimbalance_ = from._impl_.aggimbalance_;
      }
    }
    if ((cached_has_bits & 0x00004000u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_simplemid1()) != 0) {
        _this->_impl_.simplemid1_ = from._impl_.simplemid1_;
      }
    }
    if ((cached_has_bits & 0x00008000u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_simplemid2()) != 0) {
        _this->_impl_.simplemid2_ = from._impl_.simplemid2_;
      }
    }
  }
  if ((cached_has_bits & 0x001f0000u) != 0) {
    if ((cached_has_bits & 0x00010000u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_simpledivergence()) != 0) {
        _this->_impl_.simpledivergence_ = from._impl_.simpledivergence_;
      }
    }
    if ((cached_has_bits & 0x00020000u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_weightedmid1()) != 0) {
        _this->_impl_.weightedmid1_ = from._impl_.weightedmid1_;
      }
    }
    if ((cached_has_bits & 0x00040000u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_weightedmid2()) != 0) {
        _this->_impl_.weightedmid2_ = from._impl_.weightedmid2_;
      }
    }
    if ((cached_has_bits & 0x00080000u) != 0) {
      if (::absl::bit_cast<::uint64_t>(from._internal_weighteddivergence()) != 0) {
        _this->_impl_.weighteddivergence_ = from._impl_.weighteddivergence_;
      }
    }
    if ((cached_has_bits & 0x00100000u) != 0) {
      if (from._internal_sequence() != 0) {
        _this->_impl_.sequence_ = from._impl_.sequence_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MarketDataEventProto::CopyFrom(const MarketDataEventProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MarketDataEventProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MarketDataEventProto::InternalSwap(MarketDataEventProto* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.symbol_, &other->_impl_.symbol_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.exchange1_, &other->_impl_.exchange1_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.exchange2_, &other->_impl_.exchange2_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.bestbidexchange_, &other->_impl_.bestbidexchange_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.bestaskexchange_, &other->_impl_.bestaskexchange_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.sequence_)
      + sizeof(MarketDataEventProto::_impl_.sequence_)
      - PROTOBUF_FIELD_OFFSET(MarketDataEventProto, _impl_.spread12_)>(
          reinterpret_cast<char*>(&_impl_.spread12_),
          reinterpret_cast<char*>(&other->_impl_.spread12_));
}

::google::protobuf::Metadata MarketDataEventProto::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_market_5fdata_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
